"""
Build web-optimized portfolio assets.

Reads source images from their original project folders and writes optimized
copies into ../assets/. NEVER modifies a source file.

Run:  python scripts/build_assets.py
"""

import shutil
import sys
from pathlib import Path

from PIL import Image

# ----------------------------------------------------------------- config

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"

THESIS = Path(r"D:\Thesis\Pakistan_Forest_Analysis_Yearly-20260415T103732Z-3-001")
FIVERR = Path(r"D:\Workspace\me\fiverr")
ME = Path(r"D:\Workspace\me")
LUNAR = Path(r"D:\AI\Lunar-Site-Selection\outputs\figures")
PARCEL = Path(r"D:\AI\ParcelAI\docs\figures")
GEOTIME = Path(r"D:\1webgis\Geotime\android\app\src\main\res")
LIPOST = Path(r"D:\AI\LinkedIn-Autopost\theme_previews")

MAX_EDGE = 1600          # longest edge for feature images
THUMB_EDGE = 900         # longest edge for gallery thumbs
PNG_BUDGET = 500 * 1024  # above this, re-encode as JPEG
JPEG_QUALITY = 88
HARD_LIMIT = 15 * 1024 * 1024

# (source, output stem, longest edge)  -- extension decided at encode time
JOBS = [
    # --- branded gallery cards (already purpose-built, light touch only)
    (FIVERR / "gallery_1_fsi.png",  "card-fsi",  1280),
    (FIVERR / "gallery_2_ndvi.png", "card-ndvi", 1280),
    (FIVERR / "gallery_3_rvi.png",  "card-rvi",  1280),

    # --- ParcelAI
    (PARCEL / "narowal__54535_compare.png", "parcel-compare", MAX_EDGE),
    (PARCEL / "narowal__54535_overlay.png", "parcel-overlay", MAX_EDGE),

    # --- Lunar site selection
    (LUNAR / "fig_suitability_tier1.png", "lunar-suitability", MAX_EDGE),
    (LUNAR / "fig_weights.png",           "lunar-weights",     THUMB_EDGE),
    (LUNAR / "fig_sensitivity.png",       "lunar-sensitivity", THUMB_EDGE),
    (LUNAR / "fig_constraints.png",       "lunar-constraints", THUMB_EDGE),

    # --- thesis map gallery
    (THESIS / "Maps" / "Sulaiman_Weighted_FSI_Map_10m.png",   "map-fsi",       THUMB_EDGE),
    (THESIS / "Maps" / "Sulaiman_5Class_KMeans_Map_10m.png",  "map-kmeans",    THUMB_EDGE),
    (THESIS / "Maps" / "Sulaiman_DEM_Hillshade_10m.png",      "map-hillshade", THUMB_EDGE),
    (THESIS / "Composites" / "Sulaiman_ndvi_Composite.png",   "map-ndvi",      THUMB_EDGE),
    (THESIS / "Composites" / "Sulaiman_rvi_Composite.png",    "map-rvi",       THUMB_EDGE),
    (THESIS / "Graphs" / "Fig3.1_study_area_location.png",    "map-studyarea", THUMB_EDGE),
    (THESIS / "Graphs" / "Fig1.1_methodology_workflow.png",   "map-workflow",  THUMB_EDGE),
    (THESIS / "Journal_Figures_BACKUP" / "Figure_FSI_Validation_v2.png",
     "map-validation", THUMB_EDGE),

    # --- LinkedIn Autopost: real posters generated by his own theme engine
    (LIPOST / "gis_intro.png",       "li-gis",       THUMB_EDGE),
    (LIPOST / "onyx_intro.png",      "li-onyx",      THUMB_EDGE),
    (LIPOST / "editorial_intro.png", "li-editorial", THUMB_EDGE),

    # --- app icon
    (GEOTIME / "mipmap-xxxhdpi" / "ic_launcher.png", "fgt-icon", 192),
]

# PDFs whose first page becomes a cover thumbnail
PDF_JOBS = [
    (FIVERR / "Sample_1_Thesis_GIS_Report.pdf", "sample-report"),
    (FIVERR / "Sample_2_Journal_Paper.pdf",     "sample-paper"),
]

PHOTO_SRC = ME / "photo.png"

# ----------------------------------------------------------------- helpers

written: list[tuple[str, int]] = []
missing: list[str] = []


def _save(im: Image.Image, stem: str) -> None:
    """Save as PNG, or JPEG if the PNG is too heavy. Records the result."""
    if im.mode in ("RGBA", "LA", "P"):
        im = im.convert("RGBA")

    png_path = ASSETS / f"{stem}.png"
    im.save(png_path, "PNG", optimize=True)
    size = png_path.stat().st_size

    if size > PNG_BUDGET:
        jpg_path = ASSETS / f"{stem}.jpg"
        flat = Image.new("RGB", im.size, (255, 255, 255))
        if im.mode == "RGBA":
            flat.paste(im, mask=im.split()[3])
        else:
            flat.paste(im.convert("RGB"))
        flat.save(jpg_path, "JPEG", quality=JPEG_QUALITY, optimize=True,
                  progressive=True)
        if jpg_path.stat().st_size < size:
            png_path.unlink()
            written.append((jpg_path.name, jpg_path.stat().st_size))
            return
        jpg_path.unlink()

    written.append((png_path.name, size))


def _fit(im: Image.Image, edge: int) -> Image.Image:
    if max(im.size) <= edge:
        return im
    scale = edge / max(im.size)
    new = (max(1, round(im.width * scale)), max(1, round(im.height * scale)))
    return im.resize(new, Image.LANCZOS)


def do_images() -> None:
    for src, stem, edge in JOBS:
        if not src.exists():
            missing.append(str(src))
            continue
        with Image.open(src) as im:
            im.load()
            _save(_fit(im, edge), stem)


def do_photo() -> None:
    """Square-crop the headshot at two sizes."""
    if not PHOTO_SRC.exists():
        missing.append(str(PHOTO_SRC))
        return
    with Image.open(PHOTO_SRC) as im:
        im.load()
        side = min(im.size)
        # bias the crop upward so the face is not centred on the chest
        left = (im.width - side) // 2
        top = max(0, (im.height - side) // 2 - int(side * 0.12))
        sq = im.crop((left, top, left + side, top + side))
        for px, stem in ((640, "photo@2x"), (320, "photo")):
            _save(sq.resize((px, px), Image.LANCZOS), stem)


def do_pdf_covers() -> None:
    """Render page 1 of each sample PDF. Skips cleanly if PyMuPDF is absent."""
    try:
        import fitz  # PyMuPDF
    except ImportError:
        print("  ! PyMuPDF not installed - skipping PDF cover thumbnails.")
        print("    The page falls back to a typographic sample card.")
        return

    for src, stem in PDF_JOBS:
        if not src.exists():
            missing.append(str(src))
            continue
        with fitz.open(src) as doc:
            page = doc.load_page(0)
            pix = page.get_pixmap(dpi=110)
            im = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
            _save(_fit(im, THUMB_EDGE), stem)


def main() -> int:
    ASSETS.mkdir(parents=True, exist_ok=True)

    do_images()
    do_photo()
    do_pdf_covers()

    print(f"\nWrote {len(written)} files to {ASSETS}\n")
    total = 0
    oversized = []
    for name, size in sorted(written):
        total += size
        flag = ""
        if size > HARD_LIMIT:
            flag = "  <-- OVER 15 MB LIMIT"
            oversized.append(name)
        print(f"  {size/1024:9.1f} KB  {name}{flag}")
    print(f"\n  {total/1024/1024:9.2f} MB  total")

    if missing:
        print(f"\n  {len(missing)} source(s) not found:")
        for m in missing:
            print(f"    - {m}")

    if oversized:
        print(f"\nFAILED: {len(oversized)} file(s) exceed the 15 MB limit.")
        return 1

    print("\nOK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
